version: '3'
services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
    - DEBUG=false
    - POSTGRES_USER="upmeapp"
    - POSTGRES_PASS="123456"
    - POSTGRES_DB="upmeapp_development"
    expose:
      - "5432"
  app:
    build: .
    entrypoint: [bin/entry]
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    image: upme/app:latest
    ports:
      - "3000:3000"
    links:
      - postgresql
    environment:
      - RAILS_ENV="development"
